### ISSUE TITLE
Use commands.py instead of management/commands/each_one.py

### ISSUE THREAD

**Issue by Suor** [GaretJax/django-click#1]
This will allow getting rid of this rediculous deep directory structure and lots of files. It should be still possible to split commands into several files, but python way:
```
commands/
    __init__.py
    command1.py
    command2.py
    filecommands.py
    utils.py
```
with `commands/__init__.py`:
```python
from .command1 import Command1
from .command2 import Command2
from .filecommands import *
```
Different splitting srategies are possible this way: single file for command or file for some logical command group or just no splitting. Also this resembles how `models.py` was split.

**Comment by GaretJax** [comment]
That sounds interesting @Suor, but not as easy as it sounds. The current implementation just exposes the interface Django expects at the location it expects it to. There is no monkey patching or other changes to the way Django loads commands.

The change you suggest would involve changing the Django commands discovery and loading mechanism, which is a different problem from what django-click currently solves.

The current implementation is available here:
https://github.com/django/django/blob/master/django/core/management/__init__.py#L22-L31
https://github.com/django/django/blob/master/django/core/management/__init__.py#L45-L76
As you can see it is almost completely file-system based (hard to do magic stuff with modules loading) and does offer little room to hook some custom logic into it.

P.S.: Sorry for the delay in getting back to you, I just noticed that I wasn't receiving notifications for this repository.

**Comment by Suor** [comment]
It's possible to patch function in a module:
```python
from django.core import management

def find_commands(management_dir):
    return find_commands_new_way(management_dir) \
        + original_find_commands(management_dir)

# Patch
original_find_commands = management.find_commands
management.find_commands = find_commands
```

This will affect all subsequent invocations of `find_commands()` within a module. I will understand if you won't follow this road though :)

**Comment by GaretJax** [comment]
That's what I meant with "There is no monkey patching or other changes to the way Django loads commands.". :smile: I prefer to keep it that way.
