### ISSUE TITLE
Click 8 support requires a PyPI release

### ISSUE THREAD

**Issue by brianhelba** [GaretJax/django-click#32]
The recent changes in #27, to support Click 8, have not been released.

@FlipperPA Could you issue a new release on PyPI please?

**Comment by FlipperPA** [comment]
@brianhelba My apologies, I was hoping to get more into this release, but I suppose we should get it out now.

**Comment by FlipperPA** [comment]
@brianhelba Release as `2.3.0` - let me know if you run into any issues. Thanks for the nudge!
