### ISSUE TITLE
quotes arguments do not work with django 2.2

### ISSUE THREAD

**Issue by alexander-jacob** [GaretJax/django-click#9]
I migrated a project using django-click from Django 1.9 to Django 2.2

In Django 1.9 the following command worked:

```python
@click.command(help='Mailer send mail')
@click.argument('schema_url')
@click.argument('token')
@click.argument('subject')
@click.argument('body')
@click.argument('to', nargs=-1)
def command(schema_url, token, subject, body, to):
    click.echo(f'send "{subject}" to "{to}')
```
when called like this

`./manage.py mailer_send http://mailer:8000/mailer/api/schema $token "hello subject" "hello body" alex@example.org
`
With Django 2.2 the same command results in 
```python
subject = 'hello'
body = 'subject'
to = ['hello', 'body', 'alex@example.org']
```

django-click does not respect the quotes

**Comment by FlipperPA** [comment]
@alexander-jacob I'm going to take a look at this within the next week or two. Could you confirm for me which version of `click` you're running, and that this is still occurring? Thank you.

**Comment by ulgens** [comment]
Django 2.2 is EOL and the project wasn't supporting it for a long time. I think this issue can be closed.
